apiVersion: v1
kind: Service
metadata:
  name: oil-well-production-prediction
spec:
  selector:
    app: oil-well-production-prediction
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
