data:
  raw_path: "data/raw/data.csv"
  processed_path: "data/processed/clean_data.csv"

pipeline:
  target_col: "W_GAS"
  feature_cols: ["HOURS", "WHP", "WHT", "WLP", "C2M", "C3", "C4", "C5P"]

model:
  test_size: 0.2
  random_state: 42
  n_estimators: 50
