apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backend-secret
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-secrets-manager # This refers to your ClusterSecretStore
    kind: ClusterSecretStore
  target:
    name: backend-secret-k8s # K8s will automatically create this standard Secret
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: prod/oil-gas/db # The name of the secret inside AWS Secrets Manager
        property: url        # The JSON key holding the Postgres connection string