apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
type: Opaque
data:
  # Base64 encoded strings
  DB_USER: {{ .Values.database.credentials.user | b64enc }}
  DB_PASSWORD: {{ .Values.database.credentials.password | b64enc }}
  DATABASE_URL: {{ printf "postgres://%s:%s@database-svc:5432/%s" .Values.database.credentials.user .Values.database.credentials.password .Values.database.credentials.dbName | b64enc }}